### ISSUE TITLE
docker stats

### ISSUE THREAD

**Issue by sapanshah** [immuta/bakula#12]
Docker has a pretty cool command called docker stats which is exposed through the python API. It would be pretty cool to gather up those metrics.

**Comment by ericjperry** [comment]
Going to add a periodic call in dockeragent.start_container which calls ```docker stats``` and saves off the metrics associated with the topic/container in the DB. I will also add some calls to get metrics averages and stuff. Will work this in tandem with the metrics service ticket.

**Comment by ericjperry** [comment]
Turns out ```docker stats``` (the remote API) returns a stream of stats, and we don't actually need to poll. The strategy is going to be:

* Start a docker container
* Call ```Client.stats()``` (on the docker client in dockeragent) to retrieve a python generator which can be iterated over to retrieve each individual stat.
* Iterate over the generator and break when we have stopped the container (put a condition in the loop with a flag of some kind that detects when the container has been stopped and then break)
* For each stat, store as metric objects

**Comment by ericjperry** [comment]
Resolved by #57.
